id: P1BD7B4B7
initial_creation_type: ocr
source_metadata:
  volumes:
    23b698394f7b441bba5880031da6bd63:
      base_file: v066.txt
      image_group_id: I1PD96849
      title: འཕགས་པ་ཆོས་བཞི་བསྟན་པ་ཞེས་བྱ་བ་ཐེག་པ་ཆེན་པོའི་མདོ།
      total_pages: 892
      volume_number: 66
